// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjqD-GPDAAUiOhk8J5J6RXZLd3pY_rPHA',
    appId: '1:502774464499:web:88a3166c8e31868ea75c86',
    messagingSenderId: '502774464499',
    projectId: 'datn-ecbd4',
    authDomain: 'datn-ecbd4.firebaseapp.com',
    storageBucket: 'datn-ecbd4.firebasestorage.app',
    measurementId: 'G-F5KX4F4N36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCANfLj9FFj1nTLn7G5nOIDhMWK1f_6VMo',
    appId: '1:502774464499:android:82d486aa8611213fa75c86',
    messagingSenderId: '502774464499',
    projectId: 'datn-ecbd4',
    storageBucket: 'datn-ecbd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs2aLnKmh7ssRmKDSH-I7MWzwagsd6Z6I',
    appId: '1:502774464499:ios:d4d3e571158bf687a75c86',
    messagingSenderId: '502774464499',
    projectId: 'datn-ecbd4',
    storageBucket: 'datn-ecbd4.firebasestorage.app',
    iosBundleId: 'com.example.appSchools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs2aLnKmh7ssRmKDSH-I7MWzwagsd6Z6I',
    appId: '1:502774464499:ios:d4d3e571158bf687a75c86',
    messagingSenderId: '502774464499',
    projectId: 'datn-ecbd4',
    storageBucket: 'datn-ecbd4.firebasestorage.app',
    iosBundleId: 'com.example.appSchools',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjqD-GPDAAUiOhk8J5J6RXZLd3pY_rPHA',
    appId: '1:502774464499:web:b882204756b0e923a75c86',
    messagingSenderId: '502774464499',
    projectId: 'datn-ecbd4',
    authDomain: 'datn-ecbd4.firebaseapp.com',
    storageBucket: 'datn-ecbd4.firebasestorage.app',
    measurementId: 'G-NM4P4JEWZ7',
  );
}
